//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CuoiKy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleId { get; set; }
        public string Title { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> TourId { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
