//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CuoiKy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour_Destination
    {
        public int TourId { get; set; }
        public int DestinationId { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
